
# D:/Media/Work/Third Year 2015/CSC3003S/Compilers 2/Compilers 2 Project\parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'B4D70A31F88587BA854DDCF46F13A0FA'
    
_lr_action_items = {'MINUS':([4,5,6,8,9,12,15,16,17,18,19,],[-10,10,-9,-7,-4,10,-3,-2,-8,-5,-6,]),'RPAREN':([4,6,8,9,12,15,16,17,18,19,],[-10,-9,-7,-4,17,-3,-2,-8,-5,-6,]),'DIVIDE':([4,6,8,9,15,16,17,18,19,],[-10,-9,-7,14,14,14,-8,-5,-6,]),'PLUS':([4,5,6,8,9,12,15,16,17,18,19,],[-10,11,-9,-7,-4,11,-3,-2,-8,-5,-6,]),'ID':([0,3,7,10,11,13,14,],[2,4,4,4,4,4,4,]),'TIMES':([4,6,8,9,15,16,17,18,19,],[-10,-9,-7,13,13,13,-8,-5,-6,]),'$end':([1,4,5,6,8,9,15,16,17,18,19,],[0,-10,-1,-9,-7,-4,-3,-2,-8,-5,-6,]),'LPAREN':([3,7,10,11,13,14,],[7,7,7,7,7,7,]),'FLOAT_LITERAL':([3,7,10,11,13,14,],[6,6,6,6,6,6,]),'EQUAL':([2,],[3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([3,7,],[5,12,]),'statement':([0,],[1,]),'factor':([3,7,10,11,13,14,],[8,8,8,8,18,19,]),'term':([3,7,10,11,],[9,9,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ID EQUAL expression','statement',3,'p_statement_id','parse_ula.py',13),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parse_ula.py',17),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parse_ula.py',21),
  ('expression -> term','expression',1,'p_expression_term','parse_ula.py',25),
  ('term -> term TIMES factor','term',3,'p_term_times','parse_ula.py',29),
  ('term -> term DIVIDE factor','term',3,'p_term_div','parse_ula.py',33),
  ('term -> factor','term',1,'p_term_factor','parse_ula.py',37),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parse_ula.py',41),
  ('factor -> FLOAT_LITERAL','factor',1,'p_factor_float','parse_ula.py',45),
  ('factor -> ID','factor',1,'p_factor_id','parse_ula.py',49),
]
